apiVersion: v1
entries:
  karpenter:
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-02-09T09:29:47.300338+01:00"
    description: A Helm chart for Kubernetes
    digest: 00fc7da22fbd7b6fbf48dacb686efcdb3967b34a8076b3558f30177176749c89
    name: karpenter
    type: application
    urls:
    - karpenter-v0.1.0.tgz
    version: v0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-rc.0
    created: "2026-02-09T09:29:47.299734+01:00"
    description: A Helm chart for Kubernetes
    digest: 6e89a07b4688dfed0d43c81d0ee92e54e9f9d6ef4c8ea5c2acd503521a6dda46
    name: karpenter
    type: application
    urls:
    - karpenter-v0.1.0-rc.0.tgz
    version: v0.1.0-rc.0
generated: "2026-02-09T09:29:47.29898+01:00"
