apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "karpenter.fullname" . }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "karpenter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "karpenter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "karpenter.fullname" . }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  # Read
  - apiGroups: ["karpenter.k8s.gcp"]
    resources: ["gcenodeclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "karpenter.sh" ]
    resources: [ "nodepools", "nodepools/status", "nodeclaims", "nodeclaims/status", "nodeoverlays", "nodeoverlays/status" ]
    verbs: [ "get", "list", "watch" ]
  # Write
  - apiGroups: ["karpenter.k8s.gcp"]
    resources: ["gcenodeclasses", "gcenodeclasses/status"]
    verbs: ["patch", "update"]
  - apiGroups: [ "karpenter.sh" ]
    resources: [ "nodeclaims", "nodeclaims/status" ]
    verbs: [ "create", "delete", "update", "patch" ]
  - apiGroups: [ "karpenter.sh" ]
    resources: [ "nodepools", "nodepools/status" ]
    verbs: [ "update", "patch" ]
  - apiGroups: [ "karpenter.sh" ]
    resources: [ "nodeoverlays", "nodeoverlays/status" ]
    verbs: [ "update", "patch" ]
